FROM php:8.1-fpm

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions \
    apcu \
    bcmath \
    calendar \
    gd \
    gettext \
    intl \
    luasandbox \
    mysqli \
    pcntl \
    pdo_mysql \
    redis \
    shmop \
    soap \
    sockets \
    sysvsem \
    xmlrpc \
    xsl \
    zip \
    opcache \
    excimer \
    @composer

RUN apt update && apt install -y python3 telnet libvips-tools

RUN curl -L -O https://github.com/elastic/apm-agent-php/releases/download/v1.13.0/apm-agent-php_1.13.0_amd64.deb && \
    dpkg -i apm-agent-php_1.13.0_amd64.deb && \
    rm apm-agent-php_1.13.0_amd64.deb

RUN php -m
