name: "publish dev container prebuilt image"
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "devcontainers/rust/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build php dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/mooncellwiki/torappu-backend-devcontainer
          push: always
          subFolder: ./devcontainers/rust
