name: sync
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync
        uses: hhyasdf/image-sync-action@v1.1
        with:
          images_file: ./sync/images.yml
          auth_file: ./sync/auth.yml
          arch: amd64
          os: linux
        env:
          ALI_CR_USERNAME: ${{secrets.ALI_CR_USERNAME}}
          ALI_CR_PASSWORD: ${{secrets.ALI_CR_PASSWORD}}
